#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$script_dir"

main_file="Core/Src/main.c"
main_file_cpp="Core/Src/main.cpp"
include_file="Core/Inc/main.hpp"
cmake_file="cmake/stm32cubemx/CMakeLists.txt"
heap_file="Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c"


if [ -f $main_file ]; then
  mv $main_file $main_file_cpp

    # Comment out MX_FREERTOS_Init in main.cpp
  sed -i 's|MX_FREERTOS_Init();|// MX_FREERTOS_Init();|' $main_file_cpp
  
  sed -i '/\/\* USER CODE BEGIN Includes \*\//a #include "main_prog.hpp"' $main_file_cpp
  sed -i '/osKernelInitialize();/a   main_prog();' $main_file_cpp
  
  echo "#pragma once" > $include_file
  echo "" >> $include_file
  echo "// File generated by StmEpic" >> $include_file
  echo "" >> $include_file
  echo "#include \"main.h\"" >> $include_file
  echo "" >> $include_file

  sed -n '/\/\* Private variables ---------------------------------------------------------\*\//,/\/\*/p' $main_file_cpp | grep -v '/\*' | while read -r line; do
    if [ ${#line} -eq 1 ]; then
      continue
    else
      echo "extern" $line >> $include_file
    fi
  done

  rm -rf Core/Src/syscalls.c

  # Remove ../../Core/Src/syscalls.c from CMakeLists.txt
  if grep -q "../../Core/Src/syscalls.c" $cmake_file; then
    sed -i '/\.\.\/\.\.\/Core\/Src\/syscalls\.c/d' $cmake_file
  fi


  # for Latest CubeMX 6.14 with new genration schema
  if grep -q "${CMAKE_SOURCE_DIR}/Core/Src/main.c" $cmake_file; then
    sed -i 's|\${CMAKE_SOURCE_DIR}/Core/Src/main\.c|\${CMAKE_SOURCE_DIR}/Core/Src/main\.cpp|' $cmake_file
  fi

  # for CubeMX 6.13 and older
  if grep -q "../../Core/Src/main.c" $cmake_file; then
    sed -i 's|\.\./\.\./Core/Src/main\.c|../../Core/Src/main.cpp|' $cmake_file
  fi



  sed -i 's|static uint8_t ucHeap\[ configTOTAL_HEAP_SIZE \];|__attribute__((section(".ramaxis_section"))) static uint8_t ucHeap\[ configTOTAL_HEAP_SIZE \];|' $heap_file

  rm -rf CMakePresets.json
fi