#pragma once

// File generated by StmEpic

#include "main.h"

extern ADC_HandleTypeDef hadc1;
extern DCACHE_HandleTypeDef hdcache1;
extern FDCAN_HandleTypeDef hfdcan1;
extern I2C_HandleTypeDef hi2c2;
extern SPI_HandleTypeDef hspi1;
extern TIM_HandleTypeDef htim6;
extern UART_HandleTypeDef huart4;
extern PCD_HandleTypeDef hpcd_USB_OTG_FS;
